### ISSUE TITLE
Migrate signup/login to modal

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#105]
# Tasks

- [x] Create modal flow for both signup and login as this is more intuitive for when we want to prompt users to create an account in order to create a recipe
- [x] Cleanup auth only paths relationship now that login modal is used
- [x] Simplify logout process in regards to `localStorage`. Fix the bounce issue where other tab listeners are calling API as well along with trigger `localStorage` listener on main tab
- [x] Use Login modal in lieu of `<Unauthorized />` so that users can go to auth links without seeing **401**
- [x] All `<AuthRoute />` uses this behavior now
