### ISSUE TITLE
Improve Recipe Player [Part 2]

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#106]
# Tasks

- [x] add login modal & block if user is guest or unverified
- [x] Add alert for error and success flow
- [x] Block user from `/recipe/new` if not logged in
- [x] Integrate stage form with **Create Recipe** form
- [x] `/recipe/new` use less compressed layout for recipe creation
- [x] Create recipe player stages form - https://github.com/brewbean/coffee-subhelper/pull/136
- [x] Hide barista name from **Create Recipe** form

[Part 1](https://github.com/brewbean/coffee-subhelper/pull/103)
