### ISSUE TITLE
Email confirmation UI 

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#109]
# Tasks

- [x] Create `/activate` page that takes in `email` & `code` as query params
- [x] Make this page call `/verify/validate`
- [x] If code is expired, display this & allow user to resend verification code
- [x] If missing a query param  redirect them to home page
- [x] If it is an unknown user or bad verification code, display bad link message

Backend implemented
- https://github.com/brewbean/coffee-subhelper-server/issues/7
