### ISSUE TITLE
Profile page utilities

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#110]
# Tasks

- [x] Add a resend verification email button on profile page if user isn't verified & may have not gotten their email
- [ ] Add message to signup modal and to have user double check junk mail
- [ ] Add password change feature
- [ ] Add forgot password button on login page
