### ISSUE TITLE
[ brew log ] brew log page component pt. 2

### ISSUE THREAD

**Issue by m1771vw** [brewbean/client#128]
**TODO**:
- [x] Fix issue #38

**Linked Issues**
- #29, #148, #177, #178, #184, #185

**REDESIGN** 
- [ ] Mobile cards need redesign (same inspo as above) 

**Future Tasks**
- [ ] Link to the bean itself 
- [ ] Name of bean needs to be searchable in database (can use debounce/pause) 
- [ ] Change Bean Type to Name of bean(?)
- [ ] Add prompt to add recipe to recipe database
- [ ] Add reference to recipe later
- [ ] Add prompt to add bean (if bean doesn't exist) 
- [ ] Add references to your logs on Recipe page (this will be part of Recipe page)
- [ ] ~~Add references to your logs on Bean page (this will be part of Bean page)~~
