### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#137]
- [xd file](https://xd.adobelanding.com/en/xd-cloud-file-launch/?name=https%3A%2F%2Fcc-api-storage.adobe.io%2Fid%2Furn%3Aaaid%3Asc%3AUS%3A9653347e-b1b4-462f-9a69-84f402f183b7)
- implement basic walkthrough of new user flow to get to all recipe page & player. Only include recipe in mockup. We will still list other features on main page but will gray them out and say "Coming soon"

# TODO

## Home Page - (Will)
- [x] Redo hero banner / search button -> Not sure where to start?
- [x] Replace Recipe Player w/ Brew Log
- [x] Gray out / coming soon for Beans & Brew Log

## Landing Page - (James)
- [x] What are we working with? banner
- [x] Brew Type decision circles
- [x] Gray out other ones but pour over
