### ISSUE TITLE
Improve Recipe Player [Part 3]

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#140]
**Note: includes recipe page as well because integration needs both entities to be better**

# Tasks

- [x] add GIFs of pouring segment (bloom, pouring, serve)
- [x] **[ fix ]** Recipe Player doesn't work for guest/unverified  
- [x] Refactor review edits so it doesn't need a new page
- [x] `/recipe/{id}/edit` should not be deep linked
- [x] update cache correctly based on **delete** / **update** stage - **[WORKING]** #147
- [x] confirm edit page works correctly for stages as well - **big [WIP]** #145 - **[WORKING]** #147
- [x] Deep linking behavior is correct for **_Create/Detail/Edit/Reviews_** - **big [WIP]** #145 - **[WORKING]** #147
- [x] Delete recipe triggers confirmation modal
- [x] Block user from reviewing own recipe
- [x] Recipes has a section similar to recipe player that can display stages (just has a button to recipe player right now)
- [x] Make sure recipe page render instructions correctly (ex. newline styling)
- [x] Make recipe player work from details `/recipe/12/player`
- [x] recipe page leads to player correctly

[Part 1](https://github.com/brewbean/coffee-subhelper/pull/103)
[Part 2](https://github.com/brewbean/coffee-subhelper/issues/106)
