### ISSUE TITLE
Add Jest Testing for client

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#166]
### Tasks
- [ ] Unit test suite for form/input validation
- [ ] Basic DOM test for component

**Note: add more testing tasks here @jaamz @m1771vw**

### Form/Input Validation
- [ ] Input
- [ ] TextArea
- [ ] Dropdown
- [ ] Button

### Validation Validation
- [ ] Checking if types match

### Link Validation
- [ ] Header 
- [ ] Home Page
- [ ] Profile
- [ ] Footer
- [ ] Landing Page

### Checklist for Front End Testing (could possibly be outdated)

- [Checklist here](https://github.com/brewbean/wiki/blob/main/front-end-testing.md)
