### ISSUE TITLE
[ brew log ] sidebar list

### ISSUE THREAD

**Issue by jaamz** [brewbean/client#177]
# Tasks
- [x] Implement query for list
- [x] Pagination or _**load more**_ support
- [x] Add `loading`, `error` state to sidebar
- [x] Add linking to list component
- [x]  Add brew log list component layout
