### ISSUE TITLE
[ brew log ] brew log details component

### ISSUE THREAD

**Issue by m1771vw** [brewbean/client#184]
**Tasks**

- [x] Implement description area for brew log
- [x] Link to recipe entity (and to other related items for future eg beans)
- [x] Include template recipe linking
- [x] Edit/delete buttons 

🎥 &mdash; [demo](https://www.loom.com/share/f466a86fc2d34354a60530ba3941ed33)
