### ISSUE TITLE
[ brew log ] mobile layout

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#228]
# Overview
Currently sidebar does not have a mobile layout. For `/brewlog` we should just show the list view in mobile. Clicking on list goes to `/brewlog/1` &mdash; which must also maintain the query params (ex. `?page=2`). Going back in navigation should behave like going back to list view

## Tasks

- [x] Show just list view on `/brewlog` for mobile
- [x] Show just detail view for `/brewlog/{id}`
- [x] Connect links to `/brewlog` on main page &mdash; desktop & mobile view (#232)
- [x] Maintain query params when navigating &mdash; this is because our sidebar is present at all times on desktop view (#231)
