### ISSUE TITLE
[ brew log ] final touches

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#235]
# Clean up issues
- #185
- #186

# Tasks

- [x] Cache correct for every action &mdash; create, edit, delete brew log
- [x] Normalize brew log variable naming to use `BrewLog` rather than `Brewlog` &mdash; lowercase version: `brewLog`
- [x] Prompt guest & unvalidated user when they click on create brew log &mdash; **need to check unvalidated flow in future**
- [x] Show brew log not found if unaccessible due to permissions
- [x] Delete trigger modal confirmation
- [x] `src/pages/BrewLog/Edit/index.js` get rid of coupling to `<Container />` &mdash; no `isNew` prop
- [x] Add  import recipe &mdash; **_reference_** version (no form needed) (#238)
- [x] Add import recipe &mdash; **_template_** version (form needed) (#238)
- [x] Add  create from scratch &mdash; like **_template_** version but without default values (#238)
- [x] Add navigation buttons for form state navigation &mdash; doesn't use browser history API (#238)
- [x] ~~Implement delete recipe on `goBack` in form~~ &mdash; **not going to implement** - discuss in future UX meetings
