### ISSUE TITLE
[ bean ] add purchase detail section

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#271]
# Tasks

- [x] Add a section for "Where to purchase" in bean details &mdash; should allow newlines
- [x] Fix rounded right styling on `/bean` for table element
- [x] Add `purchase_info` field in Hasura &mdash; https://github.com/brewbean/graphql/pull/26
