### ISSUE TITLE
[ bean ] Switch km to m

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#275]
# Issue
- Currently km field for altitude only allows integers, but most coffee altitudes are in meters so it would be 1.6 km. Meters makes more sense for representing altitude

# Tasks

- [x] Change altitude form field to meters instead of km (#280)
- [x] Change display of altitude in bean details to meters (#280)
- [x] Change bean column from `altitude` to `altitude_start` & `altitude_end` (https://github.com/brewbean/graphql/pull/32)
- [x] Change form to accept range and single option (#282)
- [x] Render both single altitude & range (#282)

**Form toggle**
![Screen Shot 2021-04-20 at 3 44 55 PM](https://user-images.githubusercontent.com/6396042/115474591-9cd08180-a1f2-11eb-9688-48d406fc9ee3.png)
![Screen Shot 2021-04-20 at 3 44 51 PM](https://user-images.githubusercontent.com/6396042/115474592-9d691800-a1f2-11eb-9c7f-f7adf90b77ce.png)
