### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#28]
**Goal**
-  Should have a info bar that allows us to display status messages (aka _flash message_ in Elixir Phoenix)
- Examples
  - `"You've been logged out"`
  - `"Incorrect password"`
  - Possible API: ~~`<Login status={ERROR} message="Invalid input" />`~~
    - API: `<Alert>`
- [reference](https://tailwindui.com/components/application-ui/feedback/alerts)

**Tasks**
- [x] Implement API (context) for triggering status message
- [x] Implement alert UI on login page
- [x] Implement alert UI on any page (larger alert)
