### ISSUE TITLE
[ brew log ] change name

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#297]
# Overview
- brew log naming not as intuitive based on user research
- consider changing it to journal or diary

# Tasks

- [ ] Change client-side naming of journal
- [ ] Evaluate challenge of renaming `brew_log` in database
- [ ] If implemented, update all queries on client
