### ISSUE TITLE
[ bean ] basic details page

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#30]
**TODO**
- [x] Add pagination capabilities
- [x] Order Reviews by date added desc
- [x] ~~Filter / tags for better sorting coffee~~ &mdash; **adding to future milestone** #213 
- [x] ~~Add references to your logs on Bean page~~ &mdash; **adding to future milestone** #214 

**DESIGN**
- [x] Implement design based on recipes
