### ISSUE TITLE
[ search/filter] build a search bar that will narrow down the returned items

### ISSUE THREAD

**Issue by m1771vw** [brewbean/client#304]
## Goals
- Users should be able to reduce the amount of records returned to them

## Tasks 
- [x] Create search bar
- [x] Search should lower the amount of items 
- [x] Queries need to be updated to reflect searches
- [x] Need to trigger re-query with WHERE clauses when search is triggered

## Extra Thoughts
- Auto reload? Maybe a feature for the future
- Could maybe just have it be a search button first? And then do auto reload in the future?
- Should this be a URL thing? (eg. /recipe/search=?, or q?name=Coffee&roast=light, etc?)
 - Could maybe do this if search button is pressable?

## Hasura Notes 
- gt/gte/lt/lte: Greater Than, Less Than, Equal counter parts
- ilike/nilike: does a like, i stands for capital insensitive: `{title: {_like: "%amet%"}}`
- in/nin: in a list ex: `{ rating: { _in: [1,3,5] } }`
- like/nlike: does a like, capital sensitive
- nsimilar/similar: begin with `{ name: { _similar: "(A|C)%" } }` - is case sensitive
