### ISSUE TITLE
Brew Trak Recipe Logging Page Component

### ISSUE THREAD

**Issue by m1771vw** [brewbean/client#32]
**TODO**
- [x] Edit & Delete functionality
- [x] Hide ID
~~Need to show aggregate rating (is this done through Hasura?)~~ (unsure what this was for, don't think we need for brew log)
- [x] Redirect back to brew trak homepage after pressing Edit/Add
- [x] **IMPORTANT CHANGE:** Update Hasura from recipe to logs and update queries
- [x] Default recipe to private
~~Fix issue #38~~(Moved to #128)
- [x] Make mobile component
- [x] Temp change - free form bean name
- [x] Add auth (user needs to log in)

**REDESIGN** 
- [x] Redesign side bar
- [x] Redesign bean detail 
- [x] Left cards need redesign ([inspo](https://tailwindui.com/components/application-ui/lists/grid-lists)) 
~~Mobile cards need redesign (same inspo as above)~~ (Moved to #128 )

**Future Tasks**
Moved to #128 
~~Link to the bean itself~~
~~Name of bean needs to be searchable in database (can use debounce/pause)~~
~~Change Bean Type to Name of bean(?)~~
~~Add prompt to add recipe to recipe database~~
~~Add reference to recipe later~~
~~Add prompt to add bean (if bean doesn't exist)~~
~~Add references to your logs on Recipe page (this will be part of Recipe page)~~
~~Add references to your logs on Bean page (this will be part of Bean page)~~
