### ISSUE TITLE
Header Refactor

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#34]
**Details**
- Currently Header has some complex logic for displaying active links
  - Could be refactored to use `matchPath` to simplify active link checking
- Also need to implement new behavior for when user logged in vs guest (avatar display; login link; etc.)

**Tasks**

- [x] fix dropdown
- [x] use `react-router-dom` helpers to trigger active link styling (`useRouteMatch`)
- [x] implement default avatar skin & render avatar if there is a provided src (from Hasura)
- [x] add user details when user is logged in - [example](https://tailwindui.com/components/application-ui/elements/avatars#component-8b80f3012579843ce76c1c637705ddc8)
- [x] comb through logic for checking user logged in
