### ISSUE TITLE
Signup Page

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#42]
# Tasks

- [x] Create a signup page (using `"create account"` as standard vocab in lieu of writing `"sign up"`)
  - Theres a whole UX discussion on:
     - _**log in**_ vs _**sign in**_
     - _**log out**_ vs _**sign out**_
     - _**sign up**_ vs _**register**_ vs _**create account**_
- [x] Add linking to signup page in `/login` at very bottom in case user went to wrong page
- [x] Add success ~~page~~ modal after signing up that redirects to home page via link after
- [x] Confirm message `"username already taken"` & `"display name already taken"` when using existing names
- [x] Wire up signup POST to log user in as well - **_make sure confirmation modal ONLY shows if POST is successful_**

# Demo

- [Loom](https://www.loom.com/share/666cb6c0f0104c14b227269619323244) 🎥 

<img width="1792" alt="Screen Shot 2020-11-19 at 6 42 55 PM" src="https://user-images.githubusercontent.com/6396042/99751765-baf55280-2a97-11eb-9567-db4fea1cbef7.png">
