### ISSUE TITLE
UserContext double calling refresh token endpoint

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#50]
**Discussion on how to solve in-memory storage problem**
- https://github.com/FormidableLabs/urql/discussions/1178
- https://github.com/FormidableLabs/urql/discussions/1179 (urql caching)

**References**
- https://github.com/FormidableLabs/urql/pull/939

**Issue**

- Urql calling `/refetch-token` twice (in quick succession). Probably due to tying Urql lifecycle with `UserContext`
- After inspecting the issue and evaluating tradeoffs, I think the `localStorage` method for handling JWT will be adequate. Obviously with the added potential for XSS attacks, we will continue to use a short token life (~10 min), but also can add re-login sessions at a later time for sensitive tasks like buying items
- Along with email confirmation and change password, we should be able to mitigate the common attack vectors

**Not going to implement**

- [x] ~~migrate to `localStorage` JWT storage~~
  - **not required anymore**
- [x] ~~refactor logout logic using Urql suggested exchange ([doc](https://formidable.com/open-source/urql/docs/advanced/authentication/#handling-logout-with-the-error-exchange))~~
  - **overly complex way of handling logout imo since we have a lot of custom logic for refresh tokens**

**Tasks**

- [x] ~~extract Urql logic from `UserContext`~~ - using `AuthContext`
- [x] evaluate if different auth states are required ([doc](https://formidable.com/open-source/urql/docs/advanced/authentication/#cache-invalidation-on-logout))
  - **confirmed that we should probably use it for clearing cache; now implemented**
- [x] test silent refresh works as expected
- [x] test auto-logout on fail works
- [x] test logout all tabs still works
- [x] check that container, auth, redirect routes work
- [x] test guest experience works correctly
