### ISSUE TITLE
Unverified User Flow

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#53]
## Goal
- Make unverified users aware of their limited status at **_all time_***, we want every user to be verified for security reasons
  - currently only posts banner on page load. Future PRs will address users being made aware of them being unverified if they attempt to do something such as creating a recipe

## Tasks
- [x] Unverified users will have a JWT role `unverified`. We need to setup restricted access for them on Hasura
- [x] Using `is_verified` field on `barista` query, we should make sure that they are show an alert to verify their user via email on every page
- [x] ~~Add link to recheck their verification status if they clicked it (or reload)~~ - used a background event listener to trigger a change in verification status in other tabs
- [x] Add link to resend email verification
- [x] Update alerts to be able to have links
- [x] Alerts should be floating and not break layout (**_investigate_**)

## Bugs
- Forgot to give a new JWT which is necessary because old JWT has `unverified` role
- Backend fixes required to make this happen: https://github.com/brewbean/coffee-subhelper-server/pull/20
