### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by pattruong** [brewbean/client#54]
## Tasks

#125
- [x] Add a resend verification email button on profile page if user isn't verified & may have not gotten their email
- [x] Show need verification banner on profile page anytime an unverified user navigate here

**client:** #124 **server:** https://github.com/brewbean/coffee-subhelper-server/pull/22
- [x] Make sure profile editing trigger correct refresh on `barista` field
- [x] Add password change
